const languageCode = "pt_BR";

var InformationObject = {
	legacyId : "",
	parentId : "",
	qubitParentSlug : "",
	accessionNumber : "",
	identifier : "",
	title : "",
	levelOfDescription : "Processo/Dossiê",
	extentAndMedium : "",
	repository : "",
	archivalHistory : "",
	acquisition : "",
	scopeAndContent : "",
	appraisal : "",
	accruals : "",
	arrangement : "",
	accessConditions : "Documentação pública, sem restrição de acesso, observadas as disposições previstas na legislação vigente.",
	reproductionConditions : "Sem restrição, mediante autorização e compromisso de crédito",
	language : languageCode,
	script : "",
	languageNote : "",
	physicalCharacteristics : "",
	findingAids : "",
	locationOfOriginals : "",
	locationOfCopies : "",
	relatedUnitsOfDescription : "",
	publicationNote : "",
	digitalObjectPath : "",
	digitalObjectURI : "",
	generalNote : "",
	subjectAccessPoints : "",
	placeAccessPoints : "",
	nameAccessPoints : "",
	genreAccessPoints : "",
	descriptionIdentifier : "",
	institutionIdentifier : "",
	rules : "CONSELHO NACIONAL DE ARQUIVOS. Nobrade: norma brasileira de descrição arquivística. Rio de Janeiro: Conselho Nacional de Arquivos, 2006.",
	descriptionStatus : "Versão preliminar",
	levelOfDetail : "Parcial",
	revisionHistory : "",
	languageOfDescription : languageCode,
	scriptOfDescription : "",
	sources : "",
	archivistNote : "",
	publicationStatus : "Versão preliminar",
	physicalObjectName : "",
	physicalObjectLocation : "",
	physicalObjectType : "",
	alternativeIdentifiers : "",
	alternativeIdentifierLabels : "",
	eventDates : "",
	eventTypes : "",
	eventStartDates : "",
	eventEndDates : "",
	eventActors : "",
	eventActorHistories : "",
	culture : languageCode
};